openapi: 3.0.0

info:
  title: "MxToolbox SuperTool"
  description: "MxToolbox SuperTool API"
  version: "v1"

servers:
  - url: "https://api.mxtoolbox.com/api/v1/"

paths:
  /Lookup/{Command}/?argument={argument}:
    get:
        operationId: "MxToolBoxLookupParameters"
        summary: "Get MxToolBox Lookup Command - Argument Parameters"
        parameters:
          - in: path
            name: Command
            schema:
              type: string
            required: true
            default: tcp
            description: Command value. One of these blacklist, smtp, mx, a, spf, txt, ptr, cname, whois, arin, soa, tcp, http, https, ping, trace, dns.
          - in: path
            name: argument
            schema:
              type: string
            required: true
            description: Argument value for example contoso.com
        responses:
          "200":
            description: OK
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
security:
  - ApiKeyAuth: []
