openapi: 3.0.0

info:
  title: "MXToolbox SuperTool"
  description: "Look for malicious IP addresses and domains blacklisted"
  version: "v1"

servers:
  - url: "https://api.mxtoolbox.com/api/v1/"

paths:
  /Lookup/{Command}/?argument={Argument}:
    get:
        operationId: "MXToolBoxLookup"
        summary: "MXToolBox Lookup Command - Retrieve Failed blacklists which are the ones that blacklisted the Argument provided"
        parameters:
          - in: path
            name: Command
            schema:
              type: string
            required: false
            default: blacklist
            description: Command value. One of these blacklist, smtp, mx, a, spf, txt, ptr, cname, whois, arin, soa, tcp, http, https, ping, trace, dns
          - in: path
            name: Argument
            schema:
              type: string
            required: true
            description: Argument value for example contoso.com
        responses:
          "200":
            description: OK
          "403":
            description: API returned HTTP 403 Unauthorized. Check API Key provided.
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
security:
  - ApiKeyAuth: []
