openapi: 3.0.0

info:
  title: "MXToolbox SuperTool"
  description: "Look for malicious IP addresses and domains blacklisted"
  version: "v1"

servers:
  - url: "https://api.mxtoolbox.com/api/v1/"

paths:
  /Lookup/blacklist/?argument={arg}:
    get:
        operationId: "MXToolBoxLookup"
        summary: "MXToolBox Lookup Command - Argument Parameters"
        parameters:
          - in: query
            name: arg
            schema:
              type: string
            required: true
            description: Argument value for example fabrikam.com
        responses:
          "200":
            description: OK
          "403":
            description: API returned HTTP 403 Unauthorized. Check API Key provided.
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
security:
  - ApiKeyAuth: []
